### ISSUE TITLE
How to reproduce the results of state-of-the-art methods

### ISSUE THREAD

**Issue by zhanghan0112** [OpenDriveLab/OpenLane-V2#105]
Hi, thanks for your dataset!

Could you share the config of state-of-the-art methods: STSU, VectorMapNet, MapTR？

Thanks!

**Comment by sephyli** [comment]
Apologies for the inconvenience. Since we reproduced each method on seperated codebases and environments, organizing the code and configurations is challenging. We do not plan to release these part of code. 

However, you can implement thees methods described in the TopoNet paper. With the dataloader in TopoNet codebase, you can easily implement the corresponding methods on OpenLane-V2 dataset.
