### ISSUE TITLE
Confusion about evaluate metric

### ISSUE THREAD

**Issue by ljnaaa** [OpenDriveLab/OpenLane-V2#110]
Hi,I'm using this repo with lansegnet and evaluate my training with my own data, I'm wondering why need to use Chamfer distance and Frechet distance for boundary and centerline seperately. and further more i'm wondering why not use Hausdoff distance but Frechet distance as well, it seems that Hausdoff distance is more simillar to human's view? 
Thanks for your job and with for your reply

**Comment by sephyli** [comment]
Our goal is to consider direction when evaluating centerlines. The Frechet distance is widely used and highly regarded in the community, making it our preferred choice for centerline evaluation.
Regarding undirected lanelines, we opt for the Chamfer distance due to its faster computation compared to the Frechet distance, and it is widely used too.
