### ISSUE TITLE
test evaluation question

### ISSUE THREAD

**Issue by qwertyczx** [OpenDriveLab/OpenLane-V2#14]
Hi, could you explain the way of evaluation when testing DET_l? 
It seems that Frechat Distance is used. Will submission with 11 points per lane and submission with 201 points per lane be evaluated by ground truth with same points num?

**Comment by faikit** [comment]
Hi, it is similar to calculating mAP for object detection, but, instead of IoU, we use Frechat distance to measure the similarity of a pair of centerlines. As for the thresholds, they are used to decide whether a pair of centerlines is matched ( < threshold) or not. The DET_l is average over mAPs on different thresholds.

The evaluation is with 11 points for each lane, due to efficiency concerns.

**Comment by qwertyczx** [comment]
OK, Thanks!
