### ISSUE TITLE
Baseline  model question

### ISSUE THREAD

**Issue by TmacTmac1992** [OpenDriveLab/OpenLane-V2#3]
Hi, will you provide the train and test code for baseline model and provide the baseline result?

**Comment by faikit** [comment]
Thank you for your interest in our dataset.

We just released the baseline model which can be found [here](https://github.com/OpenDriveLab/OpenLane-V2#train-a-model).
We are looking forward to your try and valuable feedback.
This is a simple model for formatting the pipeline and easy modification.
![image](https://user-images.githubusercontent.com/29263416/221597519-75735bd8-953e-43b3-8d02-6f152c3cce64.png)

We show some visualizations from an overfitted model (the code for visualization is implemented in the plug-in):
![image](https://user-images.githubusercontent.com/29263416/221598045-6e85f475-d832-4540-b86d-07de7426630b.png)
![image](https://user-images.githubusercontent.com/29263416/221598097-7d12b280-4086-4c8e-8e01-06b5a2227cb9.png)
![image](https://user-images.githubusercontent.com/29263416/221598146-6e939a9c-2694-4fd3-9ab1-3a2ed36a10cd.png)

The metrics of the baseline model on the test split are reported [here](https://github.com/OpenDriveLab/OpenLane-V2#benchmark-and-leaderboard).
The score is relatively low since the baseline serves as standardization.
To improve model performance, introducing temporal information, a more complicated model, a multi-task training strategy, and heavy data augmentation would be helpful.

**You are welcome to take part in our challenge on this dataset (Track 1 OpenLane Topology)to share your insight into this task. More detail can be found on the [website](https://opendrivelab.com/AD23Challenge.html#Track1).**


PS
Data will be released soon when the uploading process is finished.
Please also stay tuned for our paper on the dataset and baseline. It will also be released soon.

**Comment by TmacTmac1992** [comment]
Thanks for your detailed feedback!
