### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by Bochicchio3** [OpenDriveLab/OpenLane-V2#64]
Hello, 
I have 32GB v100 gpus, but I still can't fit batch size 1 for the large baseline. I was wondering how do you train it and on which gpus.
I didn't find any option to lower image resolution for training,  am I wrong? 
Do you train with half precision?  
Thank you for the clarifications

**Comment by sephyli** [comment]
Hi, @Bochicchio3,

I understand the challenge you're facing, and I apologize for any inconvenience. The memory usage issue you're encountering is primarily due to the large resolution of the input images. In our setup, we're dealing with 7 surround-view images, each with a resolution of $2048 \times 1550$. To handle this, we utilize A100 GPUs with 80GB of GPU memory to meet the requirements effectively.

You can consider adding a resize function within the `train_pipeline`. By downscaling the input image resolution, you can potentially reduce the memory demands. However, the specific functionality isn't included in the current codebase. Maybe you can adapt one from [this](https://github.com/fundamentalvision/BEVFormer/blob/32b65ffd2a85c35b5f74b753f23ef34f9a85a576/projects/mmdet3d_plugin/datasets/pipelines/transform_3d.py#L292).

We do not utilize half precision during our training process.

**Comment by Bochicchio3** [comment]
I see, thank you!
